BOT_NAME = "artio_crawlers"

SPIDER_MODULES = ["artio_crawlers.spiders"]
NEWSPIDER_MODULE = "artio_crawlers.spiders"

ROBOTSTXT_OBEY = True
CONCURRENT_REQUESTS = 4
CONCURRENT_REQUESTS_PER_DOMAIN = 2
DOWNLOAD_DELAY = 1.5
RANDOMIZE_DOWNLOAD_DELAY = True
RETRY_ENABLED = True
RETRY_TIMES = 2
COOKIES_ENABLED = False
AUTOTHROTTLE_ENABLED = True
AUTOTHROTTLE_START_DELAY = 1
AUTOTHROTTLE_MAX_DELAY = 10
AUTOTHROTTLE_TARGET_CONCURRENCY = 1.0

USER_AGENT = "ArtioResearchBot/0.1"

ITEM_PIPELINES = {
    "artio_crawlers.pipelines.PostgresArtworkPipeline": 300,
}

LOG_LEVEL = "INFO"
