select
    artwork_id,
    raw_artwork_id,
    null::uuid as artist_id,
    artist_name,
    artwork_title,
    year_start,
    year_end,
    artwork_date_text,
    medium_text,
    medium_category,
    dimensions_text,
    height_cm,
    width_cm,
    depth_cm,
    price_text,
    price_numeric,
    currency_code,
    source_name,
    source_domain,
    source_url,
    image_url,
    thumbnail_url,
    description,
    {{ quality_score() }} as quality_score,
    null::text as duplicate_group_key,
    false as is_duplicate_candidate,
    crawl_timestamp,
    created_at
from {{ ref('int_artwork_normalized') }}
where source_url is not null
