select
    id as raw_event_id,
    crawl_run_id,
    {{ clean_text('source_name') }} as source_name,
    {{ clean_text('source_domain') }} as source_domain,
    {{ clean_text('source_url') }} as source_url,
    {{ clean_text('source_record_id') }} as source_record_id,
    {{ clean_text('event_type') }} as event_type,
    {{ clean_text('event_title') }} as event_title,
    {{ clean_text('venue_name') }} as venue_name,
    {{ clean_text('venue_address') }} as venue_address,
    {{ clean_text('city') }} as city,
    {{ clean_text('country') }} as country,
    start_date,
    end_date,
    opening_datetime,
    {{ clean_text('description') }} as description,
    {{ clean_text('image_url') }} as image_url,
    raw_payload,
    content_hash,
    crawl_timestamp,
    created_at,
    updated_at
from {{ source('raw', 'events') }}
