select
    id as raw_artwork_id,
    source_id,
    crawl_run_id,
    {{ clean_text('source_name') }} as source_name,
    {{ clean_text('source_domain') }} as source_domain,
    {{ clean_text('source_url') }} as source_url,
    {{ clean_text('source_record_id') }} as source_record_id,
    {{ clean_text('artist_name') }} as artist_name,
    {{ clean_text('artwork_title') }} as artwork_title,
    {{ clean_text('artwork_date_text') }} as artwork_date_text,
    {{ clean_text('medium_text') }} as medium_text,
    {{ clean_text('dimensions_text') }} as dimensions_text,
    {{ clean_text('price_text') }} as price_text,
    {{ clean_text('currency_text') }} as currency_text,
    {{ clean_text('gallery_name') }} as gallery_name,
    {{ clean_text('institution_name') }} as institution_name,
    {{ clean_text('department_name') }} as department_name,
    {{ clean_text('image_url') }} as image_url,
    {{ clean_text('thumbnail_url') }} as thumbnail_url,
    {{ clean_text('description') }} as description,
    raw_payload,
    content_hash,
    crawl_timestamp,
    created_at,
    updated_at
from {{ source('raw', 'artworks') }}
